spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://47.107.163.168:3306/auth2?useUnicode=true&characterEncoding=UTF-8&useSSL=false&jdbcCompliantTruncation=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: ***
  jpa:
    show-sql: true
  redis:
    host: 47.107.163.168
    port: 6379
    password: ***
    database: 0
server:
  port: 9098
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


